### ISSUE TITLE
tests.py example error: Contour levels must be increasing error in 

### ISSUE THREAD

**Issue by Delosari** [dfm/corner.py#76] opened 2016-02-08 18:56 UTC
Hi! Above all I want to thank you for this greate library which I discovered while working with PyMC (https://users.obs.carnegiescience.edu/cburns/ipynbs/PyMC.html)

I was trying to learn more from the examples in test.py but I got this error:

Testing 'hist2d'
 .. cutoff
 .. cutoff2
 .. basic
 .. color
 .. levels1
 .. levels2
 .. filled
 .. smooth1
 .. smooth2
 .. philsplot
 .. lowN
Traceback (most recent call last):
  File "/home/vital/git/pyResources/pyResources/Tutorials/SearchForLineInTextFile.py", line 110, in <module>
    test_hist2d()
  File "/home/vital/git/pyResources/pyResources/Tutorials/SearchForLineInTextFile.py", line 49, in test_hist2d
    _run_hist2d("lowN", N=20)
  File "/home/vital/git/pyResources/pyResources/Tutorials/SearchForLineInTextFile.py", line 31, in _run_hist2d
    corner.hist2d(x, y, ax=ax, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/corner.py", line 561, in hist2d
    cmap=white_cmap, antialiased=False)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 5652, in contourf
    return mcontour.QuadContourSet(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py", line 1424, in __init__
    ContourSet.__init__(self, ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py", line 863, in __init__
    self._process_args(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py", line 1445, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py", line 1540, in _contour_args
    self._contour_level_args(z, args)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py", line 1189, in _contour_level_args
    raise ValueError("Contour levels must be increasing")
ValueError: Contour levels must be increasing

Thanks for any advice. Also if you have any other examples I should consider first I would love to hear your opinion.

Thanks

**Comment by dfm** [comment] 2016-02-09 02:36
This is a duplicate of #68. Can you make sure that you have the most recent version of corner and try again?

**Comment by Delosari** [comment] 2016-02-09 16:11
Hello dfm. Sorry I did not see that issue.

I checked I am using corner 1.0.1 with matplotlib 1.5.1 and numpy 1.8.2 (1.6 in the matplotlib.__version__numpy). I still get the errors but I noticed some of the plots are being generated so I am learning from those.

One additional question: I am using these plots for a paper. How should I cite the library? Also for the sigmas  explanation you provide would you advice any references? Thanks again.

**Comment by mdschneider** [comment] 2016-02-10 19:23
I am also seeing this error still with corner 1.0.1 and matplotlib 1.5.1 with some of my own data sets.

However, I can execute the example in #68 without errors.

**Comment by dfm** [comment] 2016-02-10 19:55
Can you try the github master? I expect that you are finding #73… I haven't pushed that fix to pypi yet.

Let me know!

For citation: the zenodo DOI will be fine. I should mint a new one for the recent updates and rename but in the meantime you can just use the existing one. Thanks!

**Comment by Delosari** [comment] 2016-02-11 17:54
The test.py works for me and I have made progress with the other plots. Thanks a lot!

Just the last question and I will not bother you any more I promise.

I have made my plot:

https://www.dropbox.com/s/t51b9s3cmrcyyvd/Test_highDensity_triangleContourAll.png?dl=0

But I would like to increase the number of significant figures in the median and percentiles: I am displaying bayesian plot using synthetic data and I would like to show the simulation median in the plot less rounded. Can it be done?

Thanks a lot

**Comment by dfm** [comment] 2016-02-11 19:41
You can change all the titles using the `title_format` kwarg but there isn't currently a way to get finer-grain control.

**Comment by Delosari** [comment] 2016-02-11 21:04
You mean I can use the string format, for example %.5f, to change the number of decimals?

**Comment by dfm** [comment] 2016-02-11 21:05
Should work!

**Closed** 2016-05-26 15:51 UTC
